#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc
#
# NAME
#     lab-webhook - grading script for DO288 ch04s05 demo
#
# SYNOPSIS
#     lab-webhook {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve for the particular lab of awesomeness.
#
# CHANGELOG
#   * Wed Nov 01 2017 Douglas Silva <dsilva@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'

# Required by the do288 shlib
this='webhook'
title='Demo: Building Applications with a Webhook Trigger'


# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  ocp_grab_lab_files 'no-solution'

  ocp_print_prereq_header

  ocp_check_openshift_up
  ocp_check_git_repo_exists 'version'
  ocp_check_image_exists 'redhat-openjdk-18/openjdk18-openshift'
  ocp_check_nexus_maven 'org/wildfly/swarm/bom-all/2017.10.0/bom-all-2017.10.0.pom'

  ocp_print_setup_footer

}

function lab_finish {

  ocp_print_cleanup_header

  ocp_cleanup_lab_files 'no-solution'

  ocp_admin_login_on_master
  #XXX displays nothing if the project does not exist
  ocp_delete_project "${this}"
  ocp_delete_project 'common'

  ocp_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
