#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc
#
# NAME
#     lab-probes - grading script for DO288 GE ch08s02
#
# SYNOPSIS
#     lab-probes {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup or
#     cleanup for the particular lab of awesomeness.
#
# CHANGELOG
#   * Thu Nov 19 2017 Ravi Srinivasan <rsriniva@redhat.com>
#   - initial script


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do288 shlib
this='probes'
title='Guided Exercise: Activating Probes'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

function lab_start {
  project="${RHT_OCP4_DEV_USER}-${this}"

  ocp4_print_prereq_header
  ocp4_fail_if_project_exists "${project}"
  ocp4_verify_prereq_git_projects 'probes'
  ocp4_is_cluster_up

  ocp4_print_setup_header
  ocp4_grab_lab_files 'no-solution'
  ocp4_print_setup_footer

}

function lab_finish {
  project="${RHT_OCP4_DEV_USER}-${this}"
  ocp4_print_cleanup_header
  ocp4_cleanup_lab_files 'no-solution'
  ocp4_delete_project "${project}"
  ocp4_print_cleanup_footer
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
