#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc
#
# NAME
#     lab-trigger-builds - grading script for DO288 ch04s06 ge
#
# SYNOPSIS
#     lab-trigger-builds {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve for the particular lab of awesomeness.
#
# CHANGELOG
#   * Web Jun 26 2019 Iván Chavero <ichavero@redhat.com>
#   - Refactor for shared cluster
#   * Tue Nov 14 2017 Fernando Lozano <floznao@redhat.com>
#   - reproducibility fixes
#   - download container images as gzipped files
#   * Tue Nov 07 2017 Douglas Silva <dsilva@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do288 shlib
this='trigger-builds'
title='GE: Triggering Builds'

#Container images
php_url='https://github.com/RedHatTraining/DO288-apps/releases/download/OCP-4.1-1'
php_image="php-73-ubi8"

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {
  php_old="${php_image}-original.tar.gz"
  php_new="${php_image}-newer.tar.gz"

  ocp4_print_prereq_header

  ocp4_verify_local_clone_exist
  ocp4_verify_prereq_git_projects ${this}
  ocp4_is_cluster_up

  ocp4_verify_files_available_from_url "${php_url}" "${php_old}" "${php_new}"
  ocp4_fail_if_project_exists "${RHT_OCP4_DEV_USER}-${this}"

  ocp4_print_setup_header
  print_line ' Downloading required files:'
  ocp4_grab_lab_files 'no-solution'
  ocp4_download_file "${php_old}" "${labs}/${this}" "${php_url}/${php_old}"
  ocp4_download_file "${php_new}" "${labs}/${this}" "${php_url}/${php_new}"
  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_cleanup_lab_files 'no-solution'
  ocp4_login_as_developer
  #XXX displays nothing if the project does not exist
  ocp4_delete_project "${RHT_OCP4_DEV_USER}-${this}"

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
