#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-app-config - grading script for DO288 GE ch02s06
#
# SYNOPSIS
#     lab-app-config {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or
#     finish for the particular lab of awesomeness.
#
# CHANGELOG
#   * Mon Jun 03 2019 Fernando Lozano <flozano@redhat.com>
#   - Add check for the Nexus mirror group for node.js apps
#   * Tue May 28 2019 Ravi Srinivasan <rsriniva@redhat.com>
#   - Updated for shared cluster classroom env
#   * Fri Mar 29 2019 Ravi Srinivasan <rsriniva@redhat.com>
#   - Updated for OCP 4.0
#   * Thu Oct 22 2017 Ravi Srinivasan <rsriniva@redhat.com>
#   - initial script


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do288 shlib
this='app-config'
title='Guided Exercise: Injecting Configuration Data into an Application'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  ocp4_print_prereq_header
  ocp4_verify_local_clone_exist
  ocp4_is_cluster_up

  print_line ' Checking required artifacts:'
  ocp4_verify_prereq_git_projects 'app-config'
  ocp4_verify_prereq_nexus_repositories 'nodejs'

  ocp4_fail_if_project_exists "${RHT_OCP4_DEV_USER}-${this}"

  ocp4_print_setup_header
  ocp4_grab_lab_files

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_developer
  ocp4_cleanup_lab_files
  ocp4_delete_project "${RHT_OCP4_DEV_USER}-${this}"
  ocp4_verify_local_clone_clean

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
