#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc
#
# NAME
#     lab-nexus-service - grading script for DO288 ch09s04 ge
#
# SYNOPSIS
#     lab-nexus-service {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve for the particular lab of awesomeness.
#
# CHANGELOG
#   * Tue Nov 29 2017 Douglas Silva <dsilva@redhat.com>
#   - original code


PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'

# Required by the do288 shlib
this='nexus-service'
title='GE: Containerizing Nexus as a Service'

# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  ocp4_print_prereq_header

  ocp4_verify_local_clone_exist
  ocp4_is_cluster_up
  ocp4_fail_if_project_exists "${RHT_OCP4_DEV_USER}-${this}"
  ocp4_verify_prereq_git_projects 'nexus3'

  ocp4_print_setup_header
  ocp4_grab_lab_files

  #local template="${labs}/${this}/nexus-chart/values.yaml"

  #ocp4_pad "Inserting developer user name and wildcard domain on starter values file"
  #if sed -i "s/REPLACE_QUAY_USER/${RHT_OCP4_QUAY_USER}/" "${template}"
  #then
  #  print_SUCCESS
  #else
  #  print_FAIL
  #fi

  local soltemplate="${solutions}/${this}/nexus-chart/values.yaml"

  ocp4_pad "Inserting developer user name and wildcard domain on solution values file"
  if sed -i "s/REPLACE_QUAY_USER/${RHT_OCP4_QUAY_USER}/" "${soltemplate}"
  then
    print_SUCCESS
  else
    print_FAIL
  fi
  local approute="nexus3-${RHT_OCP4_DEV_USER}.${RHT_OCP4_WILDCARD_DOMAIN}"
  if sed -i "s/default/${approute}/" "${soltemplate}"
  then
    print_SUCCESS
  else
    print_FAIL
  fi
  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_developer
  ocp4_delete_project "${RHT_OCP4_DEV_USER}-${this}"

  image=nexus
  ocp4_delete_local_image "localhost/${RHT_OCP4_QUAY_USER}/${image}"

  ocp4_cleanup_lab_files

  print_line
  print_line 'If you want to perform this exercise again, you need to access quay.io'
  print_line "and delete your 'nexus' repository."
  print_line

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
