#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc
#
# NAME
#     lab-micro-java - grading script for DO288 ch09s06 ge
#
# SYNOPSIS
#     lab-micro-java {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does setup, grading,
#     cleanup, or solve for the particular lab of awesomeness.
#
# CHANGELOG
#   * Fri Jul 17 2019 Dan Kolepp <dkolepp@redhat.com>
#   - Copied from lab-manage-builds; and modified
#   - History below is from the lab-manage-builds file
#   * Thu Apr 11 2019 Ravi Srinivasan <ravis@redhat.com>
#   - Updated for OCP 4
#   * Mon Oct 30 2017 Fernando Lozano <flozano@redhat.com>
#   - add check for wildfly swarm maven BOM
#   * Tue Oct 24 2017 Douglas Silva <dsilva@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'

# Required by the do288 shlib
this='micro-java'
title='GE: Deploying An Application with Red Hat OpenShift Application Runtimes'


# This defines which subcommands are supported (setup, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  ocp4_print_prereq_header
  ocp4_verify_local_clone_exist
  ocp4_is_cluster_up
  print_line ' Checking required artifacts:'
  #ocp4_verify_prereq_nexus_repositories 'java'
  ocp4_fail_if_project_exists "${RHT_OCP4_DEV_USER}-${this}"

  ocp4_print_setup_header
  ocp4_grab_lab_files 'no-solution'

  ocp4_print_setup_footer
}

function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_developer
  ocp4_cleanup_lab_files 'no-solution'
  ocp4_delete_project "${RHT_OCP4_DEV_USER}-${this}"

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
